//////////////pizza//////////////////
const FoodDate = [
  {
    ImagePath: "../public/PizzaImages/p1.jpg",
    CardTitle: "mushroom",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "10$",
    category: "pizza",
    count: 1,
  },
  {
    ImagePath: "../public/PizzaImages/p2.jpg",
    CardTitle: "sausage",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "15.5$",
    category: "pizza",
    count: 1,
  },
  {
    ImagePath: "../public/PizzaImages/p3.jpg",
    CardTitle: "chickens",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "17.5$",
    category: "pizza",
    count: 1,
  },
  {
    ImagePath: "../public/PizzaImages/p4.jpg",
    CardTitle: "The four seasons",
    CardParagraph: "Lorem  dolor sit amet consectetur adipisicing.",
    CardPrice: "5.5$",
    category: "pizza",
    count: 1,
  },
  {
    ImagePath: "../public/PizzaImages/p5.jpg",
    CardTitle: "Four seasons cheese isides",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "7.5$",
    category: "pizza",
    count: 1,
  },
  {
    ImagePath: "../public/PizzaImages/p6.jpg",
    CardTitle: "Margarita",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "7.5$",
    category: "pizza",
    count: 1,
  },
  //////////////////Western////////////////////////
  {
    ImagePath: "../public/WesternImages/w1.jpg",
    CardTitle: "Chicken Fajita",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "25$",
    category: "Western food",
    count: 1,
  },
  {
    ImagePath: "../public/WesternImages/w2.jpg",
    CardTitle: "Scallops with Bechamel Meal",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "20$",
    category: "Western food",
    count: 1,
  },
  {
    ImagePath: "../public/WesternImages/w3.jpg",
    CardTitle: "Chicken Cordon Bleu",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "18$",
    category: "Western food",
    count: 1,
  },
  {
    ImagePath: "../public/WesternImages/w4.jpg",
    CardTitle: "Spicy Zinger Meal",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "3$",
    category: "Western food",
    count: 1,
  },
  {
    ImagePath: "../public/WesternImages/w5.jpg",
    CardTitle: "Supreme",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "8$",
    category: "Western food",
    count: 1,
  },
  {
    ImagePath: "../public/WesternImages/w6.jpg",
    CardTitle: "Crispy Chicken",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "7$",
    category: "Western food",
    count: 1,
  },
  ///////////////////Oriental///////////////////////
  {
    ImagePath: "../public/OrientleImages/c1.jpg",
    CardTitle: "Shakriya and Rice",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "29$",
    category: "Oriental food",
    count: 1,
  },
  {
    ImagePath: "../public/OrientleImages/c2.jpg",
    CardTitle: "Kabsa",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "70$",
    category: "Oriental food",
    count: 1,
  },
  {
    ImagePath: "../public/OrientleImages/c3.jpg",
    CardTitle: "Shish Barak",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "18$",
    category: "Oriental food",
    count: 1,
  },
  {
    ImagePath: "../public/OrientleImages/c4.jpg",
    CardTitle: "Kibbeh",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "25$",
    category: "Oriental food",
    count: 1,
  },
  {
    ImagePath: "../public/OrientleImages/c5.jpg",
    CardTitle: "grape leaves",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "3$",
    category: "Oriental food",
  },
  {
    ImagePath: "../public/OrientleImages/c6.jpg",
    CardTitle: "Syrian stuffed",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "9$",
    category: "Oriental food",
    count: 1,
  },
  /////////////////////////Authority///////////////////////////7
  {
    ImagePath: "../public/AuthorityImages/s1.jpg",
    CardTitle: "Tabbouleh",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "1$",
    category: "Authority",
    count: 1,
  },
  {
    ImagePath: "../public/AuthorityImages/s2.jpg",
    CardTitle: "Chicken Pasta Salad",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "4$",
    category: "Authority",
    count: 1,
  },
  {
    ImagePath: "../public/AuthorityImages/s3.jpg",
    CardTitle: "Caesar Salad",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "8$",
    category: "Authority",
    count: 1,
  },
  {
    ImagePath: "../public/AuthorityImages/s4.jpg",
    CardTitle: "Fattoush",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "2$",
    category: "Authority",
    count: 1,
  },
  {
    ImagePath: "../public/AuthorityImages/s5.jpg",
    CardTitle: "Oriental Salad",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "1.5$",
    category: "Authority",
  },
  {
    ImagePath: "../public/AuthorityImages/s6.jpg",
    CardTitle: "Rocket",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "2$",
    category: "Authority",
    count: 1,
  },
  ////////////////////Drinks/////////////////////////

  {
    ImagePath: "../public/DrinksImages/d1.jpg",
    CardTitle: "Ice Tea",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "0.25$",
    category: "drinks",
    count: 1,
  },
  {
    ImagePath: "../public/DrinksImages/d2.jpg",
    CardTitle: "Water",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "4$",
    category: "drinks",
    count: 1,
  },
  {
    ImagePath: "../public/DrinksImages/d3.jpg",
    CardTitle: "Fanta",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "1$",
    category: "drinks",
    count: 1,
  },
  {
    ImagePath: "../public/DrinksImages/d4.jpg",
    CardTitle: "Ayran",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "0.5$",
    category: "drinks",
    count: 1,
  },
  {
    ImagePath: "../public/DrinksImages/d5.jpg",
    CardTitle: "Coca-Cola",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "1.5$",
    category: "drinks",
  },
  {
    ImagePath: "../public/DrinksImages/d6.jpg",
    CardTitle: "Soda",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "2$",
    category: "drinks",
    count: 1,
  },
  ////////////////////Candies/////////////////////////

  {
    ImagePath: "../public/CandiesImages/ca1.jpg",
    CardTitle: "Pumpkin Walnut Cake",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "10$",
    category: "Candies",
    count: 1,
  },
  {
    ImagePath: "../public/CandiesImages/ca2.jpg",
    CardTitle: "Tiramisu",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "12$",
    category: "Candies",
    count: 1,
  },
  {
    ImagePath: "../public/CandiesImages/ca3.jpg",
    CardTitle: "Fruit Yogurt Parfait",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "13$",
    category: "Candies",
    count: 1,
  },
  {
    ImagePath: "../public/CandiesImages/ca4.jpg",
    CardTitle: "Mixed Berry Shortcake",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "25$",
    category: "Candies",
    count: 1,
  },
  {
    ImagePath: "../public/CandiesImages/ca5.jpg",
    CardTitle: "Chocolate Lasagna",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "15$",
    category: "Candies",
  },
  {
    ImagePath: "../public/CandiesImages/ca6.jpg",
    CardTitle: "Mixed Berry Cheesecake",
    CardParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    CardPrice: "21$",
    category: "Candies",
    count: 1,
  },
];
export default FoodDate;
